export type ArticleSection = { heading: string; paragraphs?: string[]; bullets?: string[] };
export type Article = { title: string; seoTitle: string; description: string; category: string; readTime: string; intro: string[]; sections: ArticleSection[] };

export const articles: Record<string, Article> = {
  "how-to-review-a-travel-itinerary-before-sending": {
    title: "How to Review a Travel Itinerary Before Sending It to a Client",
    seoTitle: "How to Review a Travel Itinerary Before Sending It | TourAudit",
    description: "A practical pre-send itinerary review process for travel consultants covering trip flow, timings, hotels, transfers, traveller needs and client expectations.",
    category: "Quality control", readTime: "7 min read",
    intro: ["An itinerary can be accurate and still create problems for the traveller. The hotel may be confirmed, the sightseeing may exist and the transfer may be bookable, but the trip can still feel rushed, confusing or different from what the client expected.", "That is why the final review should be more than proofreading. It should test whether the itinerary works as a complete journey. A concern found before sending may take five minutes to correct; the same concern discovered during the trip can require explanations, amendments and emergency coordination."],
    sections: [
      { heading: "1. Start with the trip summary", paragraphs: ["Before reviewing each day, confirm that the summary agrees with the detailed programme. If the itinerary says six nights, the hotel allocation should total six nights. If departure is from Zurich, the final stay and airport transfer should make sense."], bullets: ["Total days and nights", "Arrival and departure cities", "Destination sequence and nights per destination", "Traveller number and type", "Intercity transport", "Major promised activities"] },
      { heading: "2. Read it as the traveller will experience it", paragraphs: ["Do not review only whether each individual service is possible. Read every day in sequence and account for wake-up times, transfers, check-in, walking, meals, rest and possible delays. Several valid components can combine into one exhausting day."] },
      { heading: "3. Check arrival day separately", paragraphs: ["Usable time depends on immigration, baggage, airport exit, transfer duration, check-in and fatigue—not only the scheduled landing time. Fixed activities increase the risk. When flight details are uncertain, use flexible wording rather than promising a full programme."] },
      { heading: "4. Review routing and transfers", paragraphs: ["Check movement between every service, including luggage handling, station changes, vehicle-access restrictions and the last practical connection. A central hotel may still require a difficult walk from the nearest drop-off point."], bullets: ["Airport or station to hotel", "Hotel to activity and return", "Luggage on transfer days", "Reservations and seat bookings", "Vehicle access near the hotel"] },
      { heading: "5. Test the daily pace", paragraphs: ["Count the demands of the day, not just attractions: early starts, long journeys, changes, walking, queues, altitude, fixed tickets and late arrivals. Suitability changes with age, mobility and the pace promised to the client."] },
      { heading: "6. Check activity timing and operating conditions", paragraphs: ["Confirm normal opening days, seasonal operations, reservation requirements, duration, last entry, meeting points and restrictions. Do not present uncertain information as guaranteed; mark details that need live reconfirmation."] },
      { heading: "7. Review hotels beyond the star category", paragraphs: ["Review location, room and bedding configuration, meal plan, accessibility, check-in timing, taxes and practical transport access. A budget that buys a spacious hotel in one destination may provide a much smaller room in central Paris; set the expectation before the client discovers it."] },
      { heading: "8. Look for missing information", paragraphs: ["Missing information can prevent a meaningful review. Identify what must be confirmed before booking or travel."], bullets: ["Traveller ages and mobility needs", "Flight or train times", "Hotel names and locations", "Meal and room configuration", "Luggage quantity", "Pass validity", "Private versus shared services"] },
      { heading: "9. Check inclusions and expectations", paragraphs: ["Clarify guides, vehicles, tickets, meals, transfers, waiting time, porterage, taxes, free time, optional activities and walking limitations. Many complaints begin with a difference between what the consultant meant and what the client understood."] },
      { heading: "10. Complete a final consistency pass", paragraphs: ["Recheck dates, day numbers, city names, traveller and room counts, nights, transport sectors, repeated activities, contradictory inclusions and copy-and-paste remnants. Then test whether promises such as relaxed, family-friendly, luxury or accessible are supported by the daily plan."] },
      { heading: "A simple pre-send question", paragraphs: ["If I were the traveller, what part of this itinerary would I question, misunderstand or struggle to complete? That question shifts the review from document accuracy to travel reality."] },
      { heading: "Add a structured second check", paragraphs: ["TourAudit helps travel consultants review itineraries for potential planning conflicts, operational gaps and missing information before they reach the client. It supports the consultant’s final review; it does not replace destination knowledge or live operational verification."] }
    ]
  },
  "10-common-itinerary-problems": {
    title: "10 Common Itinerary Problems Travel Consultants Should Check",
    seoTitle: "10 Common Travel Itinerary Problems to Check | TourAudit",
    description: "Check these 10 common itinerary problems before sending a proposal, from night-count mismatches and poor routing to hotel location and unrealistic first days.",
    category: "Checklist", readTime: "6 min read",
    intro: ["Most itinerary problems are not dramatic errors. They are small gaps between services, timings and expectations. Each component may look acceptable on its own, yet the complete trip may not work smoothly.", "Here are ten problems worth checking before an itinerary reaches the client."],
    sections: [
      { heading: "1. The nights do not match the trip duration", paragraphs: ["A seven-day, six-night holiday should normally contain six hotel nights. Check the stated duration against every overnight stay, including night trains and early-morning departures."] },
      { heading: "2. The arrival day is overloaded", paragraphs: ["Landing time is not sightseeing start time. Immigration, baggage, transfer, check-in and fatigue reduce the usable day. Keep the programme flexible when flight timing is uncertain."] },
      { heading: "3. The sequence creates unnecessary travel", paragraphs: ["An itinerary may include the right cities in the wrong order. Review geographical flow, transport connections and the departure airport together; repeated travel over the same sector deserves attention."] },
      { heading: "4. Transfer time is treated as free time", paragraphs: ["A city-to-city movement includes check-out, reaching the station, luggage, changes, arrival, hotel transfer and check-in—not only the timetable duration."] },
      { heading: "5. Too many demanding activities are together", paragraphs: ["A mountain excursion, extensive walking and a late transfer may each be possible. Combined, they may be exhausting. Assess early starts, altitude, queues, weather exposure and late finishes as one workload."] },
      { heading: "6. Hotel location is ignored", paragraphs: ["A hotel may fit the budget but sit far from the itinerary’s activities. Check practical access, not only kilometres: pedestrian zones, steep approaches and transport frequency change the experience."] },
      { heading: "7. Operating days and seasons are missed", paragraphs: ["Museums, cable cars, boats and attractions may close on particular weekdays or operate differently by season. Verify the normal pattern and flag live details for reconfirmation."] },
      { heading: "8. Traveller details are missing", paragraphs: ["Ages affect tickets and suitability; mobility affects hotels, walking and transfers; luggage affects vehicle size. A family of four needs more detail than the label ‘family’. "] },
      { heading: "9. Transport passes do not match", paragraphs: ["A pass may not cover every day, route, reservation or service. Check validity, activation, compulsory reservations and excluded services."] },
      { heading: "10. The wording creates the wrong expectation", paragraphs: ["Words such as luxury, easy, nearby, private, guided and at leisure can mean different things to consultant and client. Explain the real scope and limitations before travel."] },
      { heading: "Why these problems survive proofreading", paragraphs: ["Proofreading finds spelling and formatting errors. Operational review asks what happens between services, whether the traveller has enough time, what assumptions remain unwritten and which detail could create a complaint."] },
      { heading: "A practical final review", paragraphs: ["Check the trip at three levels: structure (days, nights, cities, hotels and transport), flow (timing, movement, workload and usable time), and expectations (inclusions, limitations and traveller needs). TourAudit provides a structured second check; the consultant remains responsible for live verification and the final decision."] }
    ]
  },
  "why-correct-itineraries-can-be-impractical": {
    title: "Why a Correct Itinerary Can Still Be Impractical",
    seoTitle: "Why a Correct Travel Itinerary Can Be Impractical | TourAudit",
    description: "A travel itinerary can be technically accurate but operationally weak. Learn how pace, transfers, walking, timing and expectations affect real trip quality.",
    category: "Trip design", readTime: "5 min read",
    intro: ["Every hotel exists. Every attraction is open. Every train can be booked. The number of nights is correct. And yet the itinerary may still be a poor plan.", "Technical correctness confirms that the listed components are valid. Practicality asks whether a real traveller can complete them comfortably, in sequence and under normal travel conditions."],
    sections: [
      { heading: "Possibility is not suitability", paragraphs: ["An eight-minute train connection may be possible but unsuitable for a family with luggage or an elderly couple unfamiliar with the station. Good review goes beyond ‘Can this be done?’ and asks ‘Should this be recommended to this client?’"] },
      { heading: "The missing time between services", paragraphs: ["Itineraries often record main services but omit packing, check-out, station transfer, platform finding, changes, hotel transfer, luggage storage and travel to the next activity. If only train time is counted, several hours can disappear."] },
      { heading: "Walking changes the experience", paragraphs: ["Coaches may not enter historic centres, drivers may use designated drop-off points and stations may require long platform walks or level changes. Review walking together with age, mobility, weather, luggage, surfaces and the number of active days."] },
      { heading: "A relaxed itinerary can have too many commitments", paragraphs: ["Fixed commitments reduce flexibility. Three timed tickets can become stressful even over short distances because one delay affects every later reservation."], bullets: ["Early departure after a late arrival", "Back-to-back fixed entries", "Activities immediately after transfers", "No meal or rest window", "Late return before another early start"] },
      { heading: "Weather and altitude add invisible effort", paragraphs: ["Mountain travel may be operationally available but demanding due to altitude, weather exposure, queues and multiple transport stages. Preserve flexibility rather than filling every theoretical hour."] },
      { heading: "Hotel quality does not correct poor location", paragraphs: ["A well-rated hotel can weaken the itinerary if its location creates long daily transfers. Consider activity locations, early starts, late returns, local transport, luggage access and vehicle restrictions."] },
      { heading: "The plan may not match the client promise", paragraphs: ["If a trip is sold as relaxed, luxury, accessible or senior-friendly, the services and daily programme must support that promise. Vague assurances are not enough."] },
      { heading: "Operational knowledge has a time limit", paragraphs: ["Strikes, closures, maintenance, weather and overcrowding can change after a proposal is prepared. Separate what is known and included, what is normally expected and what must be reconfirmed closer to travel."] },
      { heading: "A better practicality test", bullets: ["Is the sequence sensible?", "Is there enough time around each service?", "Does the effort suit these travellers?", "Is there flexibility when something runs late?", "Does the programme match the holiday promise?", "Have important limitations been explained?"], paragraphs: ["A strong itinerary offers smooth flow, realistic breaks and correct expectations. TourAudit helps identify potential conflicts, operational gaps and missing information; its findings support—not replace—the consultant’s current knowledge and professional judgement."] }
    ]
  }
};
